import "dotenv/config";
import mongoose from "mongoose";
import Internship from "../models/Internship.js";

const internshipsData = [
  {
    title: "Artificial Intelligence Intern",
    category: "Technical",
    tag: "Generative AI & LLMs",
    iconName: "Sparkles",
    description: "Construct generative AI applications, prompt engineering pipelines, agentic AI workflows, and LLM integrations.",
    tools: ["OpenAI API", "LangChain", "Python", "Pinecone", "HuggingFace"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Machine Learning Intern",
    category: "Technical",
    tag: "AI & ML",
    iconName: "Cpu",
    description: "Train supervised/unsupervised machine learning models, neural networks, and model deployment pipelines.",
    tools: ["Python", "Scikit-Learn", "TensorFlow", "PyTorch", "Jupyter"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Cyber Security Intern",
    category: "Technical",
    tag: "Security",
    iconName: "ShieldCheck",
    description: "Perform web application penetration testing, vulnerability assessments, security log analysis, and ethical hacking.",
    tools: ["Kali Linux", "Burp Suite", "Wireshark", "Nmap", "Metasploit"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "MERN Stack Development Intern",
    category: "Technical",
    tag: "Web Engineering",
    iconName: "Globe",
    description: "Architect modern full-stack web applications with React frontend, Node/Express backend, and MongoDB database.",
    tools: ["React.js", "Node.js", "Express", "MongoDB", "JWT Auth"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Full Stack Development Intern",
    category: "Technical",
    tag: "Full Stack",
    iconName: "Code",
    description: "Master complete web application lifecycle from frontend UI creation to backend REST APIs and database design.",
    tools: ["JavaScript", "React.js", "Node.js", "SQL/NoSQL", "Git"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Data Analytics Intern",
    category: "Technical",
    tag: "Data & Analytics",
    iconName: "PieChart",
    description: "Extract business insights from complex datasets using SQL queries, Tableau dashboards, and Python analytics.",
    tools: ["SQL", "Tableau", "Excel", "Python", "Statistics"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Cisco CCNA (200-301) Intern",
    category: "Networking",
    tag: "Cisco Certification",
    iconName: "Wifi",
    description: "Prepare for official Cisco CCNA 200-301 certification while configuring real-world network lab topologies.",
    tools: ["Cisco 200-301", "Packet Tracer", "IOS CLI", "OSPF/EIGRP", "EtherChannel"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Social Media Marketing Intern",
    category: "Non-Technical",
    tag: "Growth Marketing",
    iconName: "Megaphone",
    description: "Create viral campaign strategies, influencer collaborations, organic reach growth, and paid ad boosts.",
    tools: ["Meta Ads", "TikTok Studio", "Canva", "Copywriting", "SEO"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "UI/UX Design Intern",
    category: "Technical",
    tag: "Product Design",
    iconName: "Layout",
    description: "Construct interactive Figma wireframes, mobile app UI designs, component design systems, and user research personas.",
    tools: ["Figma", "Miro", "Adobe XD", "Prototyping", "User Research"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "App Development Intern",
    category: "Technical",
    tag: "Mobile Engineering",
    iconName: "Smartphone",
    description: "Develop native and cross-platform mobile apps for Android & iOS using modern frameworks and cloud backends.",
    tools: ["Flutter", "React Native", "Android Studio", "Firebase", "Kotlin"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Data Science Intern",
    category: "Technical",
    tag: "AI & Data Science",
    iconName: "Database",
    description: "Apply statistical analysis, data cleaning, exploratory data analysis (EDA), and machine learning pipelines.",
    tools: ["Python", "Pandas", "NumPy", "Scikit-Learn", "Matplotlib"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Cloud and Networking Pro Intern",
    category: "Networking",
    tag: "Cloud & AWS Networking",
    iconName: "Cloud",
    description: "Configure AWS VPC subnets, transit gateways, Direct Connect, Route 53, and cloud network security groups.",
    tools: ["AWS VPC", "Route 53", "Terraform", "EC2", "Cloud Security"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Digital Marketing Intern",
    category: "Technical",
    tag: "Growth & Ads",
    iconName: "Megaphone",
    description: "Run conversion ad campaigns on Meta & Google Ads, optimize lead funnels, and analyze marketing ROI metrics.",
    tools: ["Meta Ads Manager", "Google Ads", "GA4", "Semrush", "Copywriting"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Ethical Hacking Intern",
    category: "Networking",
    tag: "Cyber Defense",
    iconName: "Lock",
    description: "Perform penetration testing, network vulnerability exploitation, wireless security audits, and defensive hardening.",
    tools: ["Kali Linux", "Metasploit", "Burp Suite", "Wireshark", "Nmap"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Project Management Intern",
    category: "Non-Technical",
    tag: "Agile & Management",
    iconName: "Target",
    description: "Coordinate project timelines, sprint planning, client requirements gathering, and cross-functional team management.",
    tools: ["Jira", "Asana", "Notion", "Agile Scrum", "MS Project"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Video Editing Intern",
    category: "Technical",
    tag: "Media Production",
    iconName: "Video",
    description: "Edit professional promotional video reels, corporate tutorials, motion graphics, and social media media assets.",
    tools: ["Adobe Premiere Pro", "After Effects", "CapCut Pro", "Color Grading"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Content Creation Intern",
    category: "Non-Technical",
    tag: "Creative Media",
    iconName: "FileText",
    description: "Produce high-converting video reels, carousel designs, scriptwriting, and promotional brand content.",
    tools: ["CapCut", "Canva AI", "ChatGPT", "Scriptwriting", "Photoshop"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Network Engineering Intern",
    category: "Networking",
    tag: "Enterprise Infrastructure",
    iconName: "Cpu",
    description: "Design enterprise local and wide area networks (LAN/WAN), load balancing topologies, and network monitoring.",
    tools: ["GNS3", "EVE-NG", "Cisco IOS", "BGP", "Wireshark"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "CCNA Automation Intern",
    category: "Networking",
    tag: "Network Automation",
    iconName: "Cpu",
    description: "Automate network router and switch configurations using Python script, Netmiko, Ansible, and Cisco DevNet APIs.",
    tools: ["Python", "Netmiko", "Ansible", "Cisco IOS", "REST APIs"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Network Security & Firewall Expert Intern",
    category: "Networking",
    tag: "Next-Gen Firewalls",
    iconName: "Shield",
    description: "Configure Palo Alto, Fortinet, and pfSense next-gen firewalls, IPsec VPN tunnels, NAT rules, and IPS monitoring.",
    tools: ["Palo Alto PAN-OS", "FortiGate", "pfSense", "IPsec VPN", "IDS/IPS"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "React Development Intern",
    category: "Technical",
    tag: "Frontend Engineering",
    iconName: "Globe",
    description: "Create fast, modern, responsive web user interfaces using React 19, Redux Toolkit, and dynamic CSS animations.",
    tools: ["React.js", "JavaScript ES6+", "Redux", "HTML5/CSS3", "Vite"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Frontend Development Intern",
    category: "Technical",
    tag: "Frontend Engineering",
    iconName: "Layout",
    description: "Craft pixel-perfect user interface layouts, dynamic component systems, and fluid web animations.",
    tools: ["React.js", "HTML5", "CSS Variables", "JavaScript", "Tailwind/Vanilla"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Backend Development Intern",
    category: "Technical",
    tag: "Backend Engineering",
    iconName: "Server",
    description: "Engineer high-throughput RESTful API endpoints, authentication security systems, and database optimization.",
    tools: ["Node.js", "Express.js", "MongoDB", "PostgreSQL", "Redis"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Data Engineering Intern",
    category: "Technical",
    tag: "Data Systems",
    iconName: "Database",
    description: "Build ETL pipelines, architect big data warehouses, and manage automated SQL/NoSQL database streams.",
    tools: ["Apache Spark", "Python", "SQL", "PostgreSQL", "Airflow"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Game Development Intern",
    category: "Technical",
    tag: "Gaming & 3D",
    iconName: "Gamepad2",
    description: "Develop 2D/3D interactive games using Unity and Unreal Engine, writing game physics and logic scripts.",
    tools: ["Unity 3D", "C#", "Unreal Engine", "Blender", "Physics Engine"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Dot Net Development Intern",
    category: "Technical",
    tag: "Enterprise Dev",
    iconName: "Code",
    description: "Build scalable enterprise Web APIs and microservices using C#, .NET Core, and Microsoft Azure.",
    tools: ["C#", ".NET Core", "ASP.NET", "MS SQL Server", "Azure"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Business Analyst Intern",
    category: "Technical",
    tag: "Analytics & Strategy",
    iconName: "LineChart",
    description: "Analyze business workflows, gather technical product specifications, and build executive analytics dashboards.",
    tools: ["Excel", "SQL", "Power BI", "Jira", "Business Intelligence"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Software Testing Intern",
    category: "Technical",
    tag: "Quality Assurance",
    iconName: "CheckCircle",
    description: "Perform manual & automated testing suites, write test cases, execute regression runs, and track software bugs.",
    tools: ["Selenium", "Jira", "Postman", "TestRail", "JUnit"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Graphic Design Intern",
    category: "Technical",
    tag: "Visual Media",
    iconName: "Palette",
    description: "Design corporate brand guidelines, marketing banners, social graphics, logos, and digital artwork assets.",
    tools: ["Adobe Photoshop", "Illustrator", "Canva Pro", "Figma", "InDesign"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Flutter Development Intern",
    category: "Technical",
    tag: "Cross-Platform Mobile",
    iconName: "Smartphone",
    description: "Develop high-performance cross-platform iOS and Android apps using Dart, Flutter SDK, and Firebase.",
    tools: ["Flutter", "Dart", "Firebase", "State Management", "REST API"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "MEAN Stack Development Intern",
    category: "Technical",
    tag: "Web Engineering",
    iconName: "Globe",
    description: "Build full-stack web applications using MongoDB, Express.js, Angular, and Node.js with TypeScript.",
    tools: ["Angular", "Node.js", "Express", "MongoDB", "TypeScript"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Web Development Intern",
    category: "Technical",
    tag: "Web Engineering",
    iconName: "Globe",
    description: "Build modern responsive websites and interactive web applications using HTML5, CSS3, and JavaScript.",
    tools: ["HTML5", "CSS3", "JavaScript ES6+", "Bootstrap", "Git"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "WordPress Development Intern",
    category: "Technical",
    tag: "CMS Engineering",
    iconName: "Layers",
    description: "Develop custom WordPress themes, Elementor page templates, WooCommerce stores, and PHP plugins.",
    tools: ["WordPress", "Elementor Pro", "PHP", "WooCommerce", "MySQL"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "MS SQL Database Intern",
    category: "Technical",
    tag: "Database Admin",
    iconName: "Database",
    description: "Write complex T-SQL queries, stored procedures, database indexes, triggers, and query performance tuning.",
    tools: ["MS SQL Server", "SSMS", "T-SQL", "Database Indexing", "ETL"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Sales Executive Intern",
    category: "Non-Technical",
    tag: "Sales & Revenue",
    iconName: "DollarSign",
    description: "Execute B2B corporate sales calls, client presentations, lead qualification, and CRM deal closing.",
    tools: ["HubSpot CRM", "Cold Calling", "Salesforce", "Negotiation", "CRM"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Social Media Handling Intern",
    category: "Non-Technical",
    tag: "Social Media",
    iconName: "Users",
    description: "Manage day-to-day social media accounts, community DM responses, content scheduling, and engagement.",
    tools: ["Instagram Studio", "LinkedIn", "Buffer", "Hootsuite", "Canva"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Social Media Management Intern",
    category: "Non-Technical",
    tag: "Brand Strategy",
    iconName: "Target",
    description: "Develop monthly social media calendars, brand storytelling, analytics reporting, and audience growth.",
    tools: ["Meta Business Suite", "Analytics", "Content Calendar", "Buffer"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Content Writing Intern",
    category: "Non-Technical",
    tag: "Copywriting",
    iconName: "Edit3",
    description: "Write engaging blog posts, website copy, press releases, technical documentation, and social media captions.",
    tools: ["Grammarly", "ChatGPT", "WordPress", "Google Docs", "SEO Copywriting"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Email Marketing Intern",
    category: "Non-Technical",
    tag: "Marketing Automation",
    iconName: "Mail",
    description: "Design automated email drip sequences, newsletter broadcasts, list segmentation, and open rate tracking.",
    tools: ["Mailchimp", "Brevo", "Klaviyo", "Copywriting", "A/B Testing"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Tele Calling Intern",
    category: "Non-Technical",
    tag: "Client Communication",
    iconName: "PhoneCall",
    description: "Conduct outbound lead calls, student counseling, course inquiries, and client follow-ups.",
    tools: ["CRM Dialer", "Excel", "Communication Skills", "Lead Management"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Support Calling Intern",
    category: "Non-Technical",
    tag: "Customer Support",
    iconName: "Headphones",
    description: "Provide customer support assistance, resolve student queries, track helpdesk tickets, and collect feedback.",
    tools: ["Zendesk", "Freshdesk", "CRM", "Communication", "Helpdesk"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "CCNA + CCNA Security Intern",
    category: "Networking",
    tag: "Network Security",
    iconName: "ShieldCheck",
    description: "Master core Cisco routing & switching alongside Cisco ASA Firewall rules, IPsec VPNs, and AAA security authentication.",
    tools: ["Cisco ASA", "Cisco IOS", "IPsec VPN", "Radius/TACACS+", "Wireshark"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Computer Fundamentals Intern",
    category: "Networking",
    tag: "IT Infrastructure",
    iconName: "Monitor",
    description: "Understand computer hardware architecture, OS installation, troubleshooting, BIOS setups, and basic networking.",
    tools: ["Windows Server", "Linux OS", "Hardware Diagnostics", "Command Line"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "TCP/IP Masterclass Intern",
    category: "Networking",
    tag: "Protocol Engineering",
    iconName: "Network",
    description: "Deep dive into OSI 7-layer architecture, TCP/UDP packet analysis, DNS routing, DHCP servers, and packet captures.",
    tools: ["Wireshark", "TCP/IP Model", "Packet Analysis", "DNS/DHCP", "Subnetting"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "CCNA + CCNP Advanced Intern",
    category: "Networking",
    tag: "Advanced Enterprise",
    iconName: "Server",
    description: "Master advanced routing protocols (BGP, OSPF), MPLS VPNs, enterprise switching, and high availability design.",
    tools: ["Cisco CCNP Enterprise", "BGP Routing", "MPLS", "EVE-NG", "OSPFv3"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Enterprise Networking Masterclass Intern",
    category: "Networking",
    tag: "Data Center & Architecture",
    iconName: "Globe",
    description: "Architect enterprise data center network fabrics, SD-WAN topologies, network telemetry, and disaster recovery.",
    tools: ["Cisco SD-WAN", "Data Center Networking", "BGP", "Python Scripting", "Wireshark"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Java Full Stack Development Intern",
    category: "Technical",
    tag: "Software Engineering",
    iconName: "Code",
    description: "Build end-to-end web applications with Java Spring Boot microservices on the backend and modern React on the frontend.",
    tools: ["Java", "Spring Boot", "Hibernate", "React.js", "MySQL"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Python Development Intern",
    category: "Technical",
    tag: "Backend & Automation",
    iconName: "FileCode",
    description: "Develop high-performance backend REST APIs, automation scripts, and data processing bots using Python.",
    tools: ["Python", "Django", "FastAPI", "Flask", "PostgreSQL"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Advance Excel Intern",
    category: "Technical",
    tag: "Data Processing",
    iconName: "FileSpreadsheet",
    description: "Master advanced Excel formulas (VLOOKUP, XLOOKUP, INDEX/MATCH), automated VBA macros, and financial modeling.",
    tools: ["MS Excel", "VBA Macros", "Pivot Tables", "Power Query", "Data Analysis"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Data Visualization (Power BI) Intern",
    category: "Technical",
    tag: "Business Intelligence",
    iconName: "BarChart2",
    description: "Transform raw enterprise data into interactive Power BI dashboards, DAX queries, and executive reports.",
    tools: ["Power BI", "DAX", "Power Query", "SQL", "Data Modeling"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Python Full Stack Development Intern",
    category: "Technical",
    tag: "Full Stack",
    iconName: "FileCode",
    description: "Build full-stack web applications with Django/FastAPI backend API layers and React frontend components.",
    tools: ["Python", "Django", "React.js", "PostgreSQL", "Docker"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "SEO Intern",
    category: "Technical",
    tag: "Search Engineering",
    iconName: "Search",
    description: "Perform technical SEO audits, keyword research, on-page optimization, backlink outreach, and Google Search Console analysis.",
    tools: ["Ahrefs", "Semrush", "Google Search Console", "GA4", "Screaming Frog"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Accounting Intern",
    category: "Non-Technical",
    tag: "Finance",
    iconName: "Calculator",
    description: "Assist in financial bookkeeping, invoice processing, GST documentation, and financial statement analysis.",
    tools: ["Tally Prime", "Advance Excel", "QuickBooks", "GST Filing", "Bookkeeping"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "BDE (Business Development Executive) Intern",
    category: "Non-Technical",
    tag: "Business Growth",
    iconName: "Briefcase",
    description: "Identify new market opportunities, generate qualified leads, conduct client pitch meetings, and close partnerships.",
    tools: ["LinkedIn Sales Nav", "Apollo.io", "HubSpot", "B2B Sales", "Outreach"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "HR Intern",
    category: "Non-Technical",
    tag: "Human Resources",
    iconName: "Users",
    description: "Assist in talent sourcing, candidate interview coordination, employee onboarding, and HR operations.",
    tools: ["LinkedIn Recruiter", "Keka HR", "Workday", "Excel", "Google Workspace"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "Meta & Google Ads Intern",
    category: "Non-Technical",
    tag: "Performance Ads",
    iconName: "Target",
    description: "Configure high-converting Meta Pixel and Google Search ad campaigns, optimize bidding strategies, and track ROAS.",
    tools: ["Meta Ads Manager", "Google Ads", "GA4", "A/B Testing", "ROAS Tracking"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "BDA (Business Development Associate) Intern",
    category: "Non-Technical",
    tag: "Sales & Growth",
    iconName: "Award",
    description: "Drive corporate B2B sales outreach, client relationship building, product demos, and revenue conversion.",
    tools: ["Apollo.io", "LinkedIn Sales Nav", "HubSpot CRM", "Cold Calling", "Pitching"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
  {
    title: "CCNA Network Intern",
    category: "Networking",
    tag: "Cisco Networking",
    iconName: "Server",
    description: "Configure Cisco switches, routers, VLAN topologies, subnets, OSPF routing protocols, and CLI troubleshooting.",
    tools: ["Cisco Packet Tracer", "GNS3", "Wireshark", "Cisco IOS", "Putty"],
    mode: "Online",
    price1Month: 799,
    price3Month: 1399,
    price6Month: 2399,
  },
];

const run = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for internship seed");

    let created = 0;
    let updated = 0;

    for (const item of internshipsData) {
      const existing = await Internship.findOne({ title: item.title });
      if (existing) {
        await Internship.updateOne({ _id: existing._id }, { $set: item });
        updated++;
        console.log(`Updated: ${item.title}`);
      } else {
        await Internship.create(item);
        created++;
        console.log(`Created: ${item.title}`);
      }
    }

    console.log(`Done. Created: ${created}, Updated: ${updated}, Total in file: ${internshipsData.length}`);
  } catch (error) {
    console.error("Seed error:", error.message);
  } finally {
    await mongoose.disconnect();
    console.log("MongoDB disconnected");
    process.exit(0);
  }
};

run();